import Navbar from "@/components/organisms/Navbar"
import { cn } from "@/lib/utils"
import { ThemeProvider } from "next-themes"
import { Inter } from "next/font/google"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

const RootLayout = ({ children }) => {
	return (
		<html
			lang="en"
			suppressHydrationWarning
		>
			<body
				className={cn(
					"flex h-screen w-screen flex-col divide-neutral-300 overflow-hidden border-neutral-300 bg-neutral-50 text-slate-900 transition-all duration-500 ease-in-out dark:divide-neutral-700 dark:border-neutral-700 dark:bg-neutral-950 dark:text-slate-200",
					inter.className
				)}
			>
				<ThemeProvider
					attribute="class"
					defaultTheme="dark"
					enableSystem
					disableTransitionOnChange
				>
					<Navbar />
					<main className="flex w-full flex-1 flex-col">
						{children}
					</main>
				</ThemeProvider>
			</body>
		</html>
	)
}

export default RootLayout
